//
// Created by matin on 02/02/24.
//

#ifndef GSTREAMER1_0_DRPAI_PROPERTIES_H
#define GSTREAMER1_0_DRPAI_PROPERTIES_H

enum GstDRPAI_Properties {
    PROP_0,
    PROP_MULTITHREAD,
    PROP_MODEL,
    PROP_PP_PROPERTIES,
    PROP_SHOW_FPS,
    PROP_SHOW_TIME,
    PROP_LOG_DETECTS,
    PROP_STOP_ERROR,
    PROP_LOG_SERVER,
    PROP_LOG_EXEC_TIME,

    PROP_MAX_VIDEO_RATE,
    PROP_MAX_DRPAI_RATE,
    PROP_SMOOTH_VIDEO_RATE,
    PROP_SMOOTH_DRPAI_RATE,
};

#endif //GSTREAMER1_0_DRPAI_PROPERTIES_H
