//
// Created by matin on 02/02/24.
//

#ifndef GSTREAMER1_0_DRPAI_PROPERTIES_H
#define GSTREAMER1_0_DRPAI_PROPERTIES_H

enum GstDRPAI_Properties {
    PROP_0,
    PROP_MULTITHREAD,
    PROP_MODEL,
    PROP_PP_PROPERTIES,
    PROP_SHOW_FPS,
    PROP_SHOW_TIME,
    PROP_SHOW_BBOX,
    PROP_LOG_DETECTS,
    PROP_STOP_ERROR,
    PROP_LOG_SERVER,
    PROP_LOG_EXEC_TIME,

    PROP_TRACKING,
    PROP_SHOW_TRACK_ID,
    PROP_SMOOTH_BBOX_RATE,
    PROP_HISTORY_LENGTH,
    PROP_TRACK_SECONDS,
    PROP_DOA_THRESHOLD,

    PROP_FILTER_NMS,
    PROP_FILTER_PROB,
    PROP_FILTER_SHOW,
    PROP_FILTER_CLASS,
    PROP_FILTER_LEFT,
    PROP_FILTER_TOP,
    PROP_FILTER_WIDTH,
    PROP_FILTER_HEIGHT,

    PROP_MAX_VIDEO_RATE,
    PROP_MAX_DRPAI_RATE,
    PROP_SMOOTH_VIDEO_RATE,
    PROP_SMOOTH_DRPAI_RATE,

    PROP_BITMAP_SAVE_DIR,
    PROP_BITMAP_SAVE_MINUTES,
    PROP_BITMAP_SAVE_PROB,
    PROP_BITMAP_SAVE_CLASS,
};

#endif //GSTREAMER1_0_DRPAI_PROPERTIES_H
