name: Gstreamer DRP-AI Make CI

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install Dependencies
      run: sudo apt install -y -f meson ninja-build gstreamer1.0-tools libgstreamer1.0-dev libunwind-dev
      
    - name: setup meson
      run: meson setup build
      
    - name: make
      run: ninja -C build
      
    - name: gst-inspect
      run: gst-inspect-1.0 build/gst-plugin/libgstdrpai.so

  build-aarch64-yocto-rpm:
  
    needs: build
    runs-on: DC02
    
    steps:    
    - uses: actions/checkout@v3
      with:
        repository: MistySOM/rzg2l
        path: rzg2l
        ref: master
        submodules: true

    - uses: actions/checkout@v3
      with:
        path: gstreamer1.0-drpai

    - run: |
        rm -rf rzg2l/Build/meta-mistysom/recipes-drpai/gstreamer1.0-drpai
        cp -r gstreamer1.0-drpai rzg2l/Build/meta-mistysom/recipes-drpai/
        echo "SRC_URI = \"git://$(pwd)/rzg2l/Build/meta-mistysom/recipes-drpai/gstreamer1.0-drpai;protocol=file\"" >> gstreamer1.0-drpai rzg2l/Build/meta-mistysom/recipes-drpai/gstreamer1.0-drpai.bb
        sed -i -e 's/bitbake mistysom-image/bitbake gstreamer1.0-drpai/g' rzg2l/Build/exec.sh
        sed -i -e 's/\/tmp\/deploy\/images/\/tmp\/deploy\/rpm\/aarch64/g' rzg2l/Build/exec.sh

    - name: Build the Docker image
      run: cd rzg2l/Build && ./build.sh;
    
    - name: Run the Docker image and build output files
      run: cd rzg2l/Build && ./run.sh -c /home/github/rzg2l-cache;

    - name: List files that are generated
      run: ls -lah rzg2l/Build/output/
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: output-files
        path: rzg2l/Build/output/
