name: Gstreamer DRP-AI Make CI

on:
  push:
    branches: [ "master", "develop", "deeppose" ]
  pull_request:
    branches: [ "master", "develop", "deeppose" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install Dependencies
      run: sudo apt update && sudo apt install -y -f meson ninja-build gstreamer1.0-tools libgstreamer1.0-dev libunwind-dev libopencv-dev
      
    - name: setup meson
      run: meson setup build
      
    - name: compile
      run: meson compile -C build

    - name: test
      run: meson test -C build
      
    - name: gst-inspect
      run: gst-inspect-1.0 build/gst-plugin/libgstdrpai.so

  build-aarch64-yocto-rpm:
  
    needs: build
    runs-on: DC02
    
    steps:    
    - uses: actions/checkout@v4
      with:
        repository: MistySOM/rzv2l
        path: rzv2l
        ref: master
        submodules: true

    - uses: actions/checkout@v4
      with:
        path: gstreamer1.0-drpai

    - name: Replace the RZV2L gstreamer1.0-drpai with the current one.
      run: |
        mv gstreamer1.0-drpai rzv2l/Build/meta-mistysom/recipes-drpai/gstreamer1.0-drpai/files
        mv -f rzv2l/Build/meta-mistysom/recipes-drpai/gstreamer1.0-drpai/files/bitbake-recipes/* rzv2l/Build/meta-mistysom/recipes-drpai/gstreamer1.0-drpai
        sed -i -e 's|git://github.com/MistySOM/gstreamer1.0-drpai.git;branch=master|file://.|g' rzv2l/Build/meta-mistysom/recipes-drpai/gstreamer1.0-drpai/gstreamer1.0-drpai.inc
        echo "S = \"\${WORKDIR}\"" >> rzv2l/Build/meta-mistysom/recipes-drpai/gstreamer1.0-drpai/gstreamer1.0-drpai.inc

    - name: Change the build to only gstreamer1.0-drpai
      run: |
        sed -i -e 's/bitbake mistysom-image/bitbake gstreamer1.0-drpai gstreamer1.0-drpai-yolo gstreamer1.0-drpai-deeppose/g' rzv2l/Build/exec.sh
        sed -i -e 's|/tmp/deploy/images/|/tmp/deploy/rpm/aarch64/gstreamer1.0-drpai*|g' rzv2l/Build/exec.sh

    - name: Build the Docker image
      run: cd rzv2l/Build && ./build.sh;
    
    - name: Run the Docker image and build output files
      run: cd rzv2l/Build && ./run.sh -c /home/github/rzv2l-cache;

    - name: List files that are generated
      run: ls -lah rzv2l/Build/output/
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: rpm-files
        path: rzv2l/Build/output/
