name: Gstreamer DRP-AI Make CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install Dependencies
      run: sudo apt install -y -f meson ninja-build gstreamer1.0-tools libgstreamer1.0-dev libunwind-dev
      
    - name: setup meson
      run: meson setup build
      
    - name: make
      run: ninja -C build
      
    - name: gst-inspect
      run: gst-inspect-1.0 build/gst-plugin/libgstdrpai.so
